export const useInfoStore = definePiniaStore('info', {
  state: (): ICreateInfoStore => ({
    jp: {
      name: '私はエゴるで',
      hobbies: [''],
      quotes: [''],
      age: '16歳だ',
      info: 'ITが好きなんだ',
      techText: '知っているtechs:',
    },
    rus: {
      name: 'Меня зовут Егор',
      hobbies: [''],
      quotes: [''],
      age: 'Мне 16 лет',
      info: 'Мне нравится программирование',
      techText: 'Technologies stack:',
    },
    eng: {
      name: 'My name is Egor',
      hobbies: [''],
      quotes: [''],
      age: "I'm 16",
      info: 'I enjoy coding',
      techText: 'Я знаю:',
    },
    profileImage: 'https://avatars.githubusercontent.com/u/103949460?v=4',
    techs: [
      'React',
      'Vue',
      'Solid',
      'Next',
      'Nuxt',
      'Nest',
      'Express',
      'mongoose',
      'typeorm',
      'websockets',
      'graphql',
      'apollo',
      'RTK',
      'Vuex',
      'Pinia',
      'Jest',
      'Cypress',
      'supertest',
      '...  ',
    ],
  }),
  persist: false,
})
