name: github actions
on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-varsion: [ 17.x ]
    steps:
      - uses: actions/checkout@v3

      - name: ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node_version: ${{matrix.node-version}}



      - name: install modules
        run: pnpm install
      - name: run tests
        run: pnpm run test
