name: "github actions"
on:
  push:
    branches: ["master", "dev"]
  pull_request:
    branches: ["master"]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 19.x ]
    steps:
      - uses: actions/checkout@v3
      - name: ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node_version: ${{matrix.node-version}}
      - name: install pnpm
      - uses: pnpm/action-setup@v2
        with:
          version: 7.26.3
      - name: install modules
        run: pnpm install
      - name: run tests
        run: pnpm test
